package view;

import controller.ControladorJuego;
//import static java.awt.SystemColor.control;
//import java.awt.event.ActionEvent;
import view.GUIJuego;
import model.*;
/**
 *
 * @author mjlop
 */
public class GUIInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIInicio.class.getName());

    /**
     * Creates new form GUIInicio
     */
    
    private Sound sonido = new Sound();
    
    public GUIInicio() {
        initComponents();
        sonido.musicaFondoPrincipal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboColor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboColor.setBackground(new java.awt.Color(0, 102, 153));
        comboColor.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        comboColor.setForeground(new java.awt.Color(255, 255, 255));
        comboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Amarillo", "Azul", "Verde" }));
        comboColor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        comboColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboColorActionPerformed(evt);
            }
        });
        getContentPane().add(comboColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 110, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("Selección de color");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, 40));

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton.png"))); // NOI18N
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        btnInstrucciones.setBackground(new java.awt.Color(0, 102, 153));
        btnInstrucciones.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        btnInstrucciones.setText("Instrucciones");
        btnInstrucciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 130, 40));

        btnHistoria.setBackground(new java.awt.Color(0, 102, 153));
        btnHistoria.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnHistoria.setForeground(new java.awt.Color(255, 255, 255));
        btnHistoria.setText("Historia");
        btnHistoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 90, 40));

        btnCreditos.setBackground(new java.awt.Color(0, 102, 153));
        btnCreditos.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnCreditos.setForeground(new java.awt.Color(255, 255, 255));
        btnCreditos.setText("Créditos");
        btnCreditos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 80, 40));

        imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgInicio_1.png"))); // NOI18N
        getContentPane().add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        int colorId = comboColor.getSelectedIndex();
      
        ControladorJuego ctrl = new ControladorJuego(colorId);
        
        GUIJuego v2 = new GUIJuego(ctrl);
        v2.setLocationRelativeTo(null);
        v2.setVisible(true);
        this.dispose();
        sonido.click();
        sonido.detenerFondo();
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreditosActionPerformed

    private void btnHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaActionPerformed
        GUIHistoria historia = new GUIHistoria();
        historia.setVisible(true);
        historia.setLocationRelativeTo(null);
        this.setVisible(false);
        sonido.click();
        sonido.detenerFondo();
    }//GEN-LAST:event_btnHistoriaActionPerformed

    private void comboColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboColorActionPerformed

    private void btnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccionesActionPerformed
        GUIInstrucciones inst = new GUIInstrucciones();
        inst.setVisible(true);
        inst.setLocationRelativeTo(null);
        this.setVisible(false);
        sonido.click();
        sonido.detenerFondo();
    }//GEN-LAST:event_btnInstruccionesActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JComboBox<String> comboColor;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
