/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import model.TableroCoordenadas;

/**
 *
 * @author mjlop
 */
public class PanelTablero extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    private TableroCoordenadas tablero;

    public JLabel getImgFichaAm() {
        return imgFichaAm;
    }

    public JLabel getImgFichaAz() {
        return imgFichaAz;
    }

    public JLabel getImgFichaR() {
        return imgFichaR;
    }

    public JLabel getImgFichaV() {
        return imgFichaV;
    }

    
    
    public void setTablero(TableroCoordenadas tablero) {
    this.tablero = tablero;
    }
    
    
    public PanelTablero() {
        initComponents();

        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                Point p = e.getPoint();
                moverFicha(p);
            }

        });
    }

    public void moverFicha(Point p) {
        //Clase point
        imgFichaV.setLocation(p);
        System.out.println("Coordenadas : " + p.x + " , " + p.y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        imgFichaR = new javax.swing.JLabel();
        imgFichaAm = new javax.swing.JLabel();
        imgFichaAz = new javax.swing.JLabel();
        imgFichaV = new javax.swing.JLabel();
        imgTablero = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgFichaR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FichaRoja.png"))); // NOI18N
        add(imgFichaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 20, -1));

        imgFichaAm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FichaAmarilla.png"))); // NOI18N
        add(imgFichaAm, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        imgFichaAz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FichaAzul.png"))); // NOI18N
        add(imgFichaAz, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, 30));

        imgFichaV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FichaVerde.png"))); // NOI18N
        add(imgFichaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, 30));

        imgTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tablerografico.png"))); // NOI18N
        imgTablero.setText("Tablero");
        add(imgTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void moverFicha(int colorId, int x, int y) {
        JLabel lbl = labelJugador(colorId);
        if(lbl != null)
        lbl.setLocation(x, y)
        ;
    }

    public JLabel labelJugador(int colorId) {
        if (colorId == 0) {
            return imgFichaV; //rojo
        }
         if (colorId == 1) {
            return imgFichaV; // amarillo
        }
          if (colorId == 2) {
            return imgFichaV; //azul
        }
           if (colorId == 3) {
            return imgFichaV; //
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFichaAm;
    private javax.swing.JLabel imgFichaAz;
    private javax.swing.JLabel imgFichaR;
    private javax.swing.JLabel imgFichaV;
    private javax.swing.JLabel imgTablero;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
