package view;

import javax.swing.JLabel;
import model.TableroCoordenadas;

/**
 *
 * @author mjlop
 */
public class PanelTablero extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    private TableroCoordenadas tablero;

    public JLabel getlblFichaAm() {
        return lblFichaAm;
    }

    public JLabel getlblFichaAz() {
        return lblFichaAz;
    }

    public JLabel getlblFichaR() {
        return lblFichaR;
    }

    public JLabel getlblFichaV() {
        return lblFichaV;
    }

    public PanelTablero() {
        initComponents();
        setComponentZOrder(imgTablero, getComponentCount() - 1);
    }

    public void moverFicha(int colorId, int x, int y) {
        javax.swing.JLabel lbl = labelJugador(colorId);
        if (lbl != null) {
            lbl.setLocation(x, y);
            // poner la ficha al frente para garantizar visibilidad
            setComponentZOrder(lbl, 0); // 0 = arriba de todo
            revalidate();
            repaint();
        }
    }

    public JLabel labelJugador(int colorId) {
        if (colorId == 0) {
            return lblFichaR; //rojo
        }
        if (colorId == 1) {
            return lblFichaAm; // amarillo
        }
        if (colorId == 2) {
            return lblFichaAz; //azul
        }
        if (colorId == 3) {
            return lblFichaV; //verde
        }
        return null;
    }

    public void setTablero(TableroCoordenadas tablero) {
        this.tablero = tablero;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        lblFichaR = new javax.swing.JLabel();
        lblFichaAm = new javax.swing.JLabel();
        lblFichaAz = new javax.swing.JLabel();
        lblFichaV = new javax.swing.JLabel();
        imgTablero = new javax.swing.JLabel();

        setLayout(null);

        lblFichaR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FichaRoja.png"))); // NOI18N
        add(lblFichaR);
        lblFichaR.setBounds(80, 70, 20, 31);

        lblFichaAm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FichaAmarilla.png"))); // NOI18N
        add(lblFichaAm);
        lblFichaAm.setBounds(400, 390, 21, 32);

        lblFichaAz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FichaAzul.png"))); // NOI18N
        add(lblFichaAz);
        lblFichaAz.setBounds(400, 70, 21, 30);

        lblFichaV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FichaVerde.png"))); // NOI18N
        add(lblFichaV);
        lblFichaV.setBounds(80, 390, 21, 30);

        imgTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tablerografico.png"))); // NOI18N
        imgTablero.setText("Tablero");
        add(imgTablero);
        imgTablero.setBounds(0, 0, 500, 500);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgTablero;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblFichaAm;
    private javax.swing.JLabel lblFichaAz;
    private javax.swing.JLabel lblFichaR;
    private javax.swing.JLabel lblFichaV;
    // End of variables declaration//GEN-END:variables
}
