package view;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author mjlop
 */
public class PanelControl extends javax.swing.JPanel {

    private String puntos;

    /**
     * Creates new form PanelControl
     */
    public PanelControl() {
        initComponents();
    }

    ///
    //se modifica para recibir el vaolor del dado
    public void setTextoNumeroDado(int valor) {
        lblNumeroDado.setText("Numero dado: " + valor);
    }

    public void setTextoTurno(String texto) {
        lblFichaTurno.setText("Ficha turno: " + texto);
    }

    public JLabel getTxtTiempo() {
        return txtTiempo;
    }
// set para label de tiempo...
    public void setTxtTiempo(int valor) {
        txtTiempo.setText("Tiempo: "+ valor);
    }

    public void setTxtPuntosJugador(int puntosJugador) {
        this.txtPuntosJugador.setText("Puntos J:" + puntosJugador);
    }

    public void setTxtPuntosOponente(int puntosOponente) {
        this.txtPuntosOponente.setText("Puntos O:"+ puntosOponente);
    }
    
    public JButton getBtnDice() {
        return btnDice;
    }

    public JButton getBtnMenu() {
        return btnMenu;
    }

    public JButton getBtnReinicio() {
        return btnReinicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDice = new javax.swing.JButton();
        btnReinicio = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lblNumeroDado = new javax.swing.JLabel();
        lblFichaTurno = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JLabel();
        txtPuntosJugador = new javax.swing.JLabel();
        txtPuntosOponente = new javax.swing.JLabel();

        btnDice.setText("Dado");
        btnDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiceActionPerformed(evt);
            }
        });

        btnReinicio.setText("Reset");
        btnReinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinicioActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        lblNumeroDado.setText("Número Dado");

        lblFichaTurno.setText("Ficha Turno");

        txtTiempo.setText("Tiempo");

        txtPuntosJugador.setText("Puntos Jugador");

        txtPuntosOponente.setText("Puntos Oponente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPuntosOponente)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDice)
                                    .addComponent(txtPuntosJugador)
                                    .addComponent(lblNumeroDado)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblFichaTurno))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnMenu)
                                    .addComponent(btnReinicio)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(txtTiempo)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnDice)
                .addGap(18, 18, 18)
                .addComponent(lblNumeroDado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFichaTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPuntosJugador)
                .addGap(18, 18, 18)
                .addComponent(txtPuntosOponente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTiempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnReinicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenu)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDiceActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReinicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDice;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JLabel lblFichaTurno;
    private javax.swing.JLabel lblNumeroDado;
    private javax.swing.JLabel txtPuntosJugador;
    private javax.swing.JLabel txtPuntosOponente;
    private javax.swing.JLabel txtTiempo;
    // End of variables declaration//GEN-END:variables
}
